LOCAL_SKILL_LIBRARY_PATH: .cache/open_creator/skill_library
REMOTE_SKILL_LIBRARY_PATH: .cache/open_creator/remote
LOCAL_SKILL_LIBRARY_VECTORD_PATH: .cache/open_creator/vectordb/
PROMPT_CACHE_HISTORY_PATH: .cache/open_creator/prompt_cache/history.txt
SKILL_EXTRACT_AGENT_CACHE_PATH: .cache/open_creator/llm_cache
OFFICIAL_SKILL_LIBRARY_PATH: timedomain/skill-library
OFFICIAL_SKILL_LIBRARY_TEMPLATE_PATH: timedomain/skill-library-template
AGENT_MODEL: gpt-3.5-turbo-16k-0613
RUN_HUMAN_CONFIRM: false
